### ISSUE TITLE
[xcat-inventory-osimage] As an admin, how to use xCAT osimage object

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#100]
The user scenario about how to use xCAT osimage object from admin point of view.

**Comment by neo954** [comment]
Scenario One - Duplicate an existing `osimage`

* The existing `osimage` definition is a  non-xCAT default, heavily customized, `osimage`, with a long list of `otherpkglist` and heavily customized post-install script.
* Need to duplicate the existing `osimage`. And then use the duplicated `osimage` for updating.

**Comment by zet809** [comment]
The idea here have been included in the proposal that we want to show to mark, so, close this task.
