### ISSUE TITLE
Add test case for issue 1002:lsvm command does not work for kvm VMs

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#111]
Add test case for issue xcat2/xcat-core#1002

**Comment by hu-weihua** [comment]
Junxia has touched this task before but  not finished it, she listed the test cases need to add in comment of xcat2/xcat-core#3483. FYI

**Comment by tingtli** [comment]
According to the comments in issue #3483, following cases should be added.
lsvm_vm
lsvm_kvmhost
lsvm_h
lsvm_a
lsvm_all
lsvm_noderanage
Note:such cases below discussed with Mark and I will add later after this sprint
lsvm_mixed_vm_up_running
lsvm_mixed_vm_exist_and_not
lsvm_mixed_vm_defined_and_not
lsvm_mixed_vm_diskfull_diskless
lsvm_mixed_vm_running_and_off
lsvm_mixed_vm_and_not_vm

Cases need to modify:
lsvm_node
