### ISSUE TITLE
Add test case for issue 711: error in makedns

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#113]
Add test case for issue xcat2/xcat-core#711

**Comment by neo954** [comment]
@hu-weihua, why we need add test case for issue xcat2/xcat-core#711 ? Issue xcat2/xcat-core#711 is not even a bug. And it cannot not be recreated.

Is xCAT existing test case not good enough for `makedns`? Do we need to increase test coverage?
