### ISSUE TITLE
Investigate sysrq support in conserver

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat2-task-management#115]
- [x] Try to invoke sysrq with conserver / ipmitool
- [x] understand how break sequence and sysrq work

**Comment by jjohnson42** [comment]
ipmitool requires ~B to send a break.

**Comment by jjohnson42** [comment]
conserver never has natively supported the key sequence, confluent has natively supported IPMI break.

**Comment by chenglch** [comment]
@jjohnson42 , thanks, seems confluent use `SshShell(conapi.Console)` as the ssh console plugin, is there any way for a ssh based console to send a break ?
