### ISSUE TITLE
Feature verification test: syncfiles 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#119]
What to do:

* [x] offer a test plan for [syncfiles verification test](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-syncfiles)
* [x] finish the test before 2.14.1 release depending on above plan

Refer to PR xcat2/xcat-core#5123
Refer to task #58

**Comment by neo954** [comment]
The test plan is updated. Any comment is welcome.

**Comment by hu-weihua** [comment]
@neo954 , We have had ``syncfile`` ( implemented by ``updatenode -F``) function for long time. The biggest change this time is using ``scp`` method(``updatenode -F -r /bin/scp``), we used ``rsync`` method originally. So the focus of this test is not to test ``updatenode -F``, it should be test sync file with ``scp`` way, and do regression for ``rsync`` way.

**Comment by immarvin** [comment]
hi @neo954 , the design looks good. I agree with @hu-weihua that the scope should be restricted to `updatenode -F -r /usr/bin/scp`. one question is,  do the existing cases cover the `updatenode -F`? @hu-weihua 

one test point  not mentioned in your design is the `EXECUTE`,`EXECUTEALWAYS` in syncfiles. For `updatenode -F -r /usr/bin/scp`, `EXECUTE` is not supported , only `EXECUTEALWAYS` is supported. refer to http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html?highlight=syncfile for the details on `EXECUTEALWAYS`
