### ISSUE TITLE
Investigate conman and parallel command using console

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat2-task-management#122]
Feature requests about consoles:
pcons feature: https://github.com/xcat2/xcat-core/issues/5167
console broadcast mode: https://github.com/xcat2/xcat-core/issues/5134

- [ ] Investigate how conman work in console broadcast mode
- [ ] Parallel console command in xcat or goconserver?

**Comment by immarvin** [comment]
hi @chenglch , would you please add some comment in ticket https://github.com/xcat2/xcat-core/issues/5167? seems the user does not get enough information from our doc, thanks

**Comment by chenglch** [comment]
Duplicated, has been covered in https://github.com/xcat2/xcat2-task-management/issues/159
