### ISSUE TITLE
Offer test case for rvitals Power Supply Redundancy function 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#14]
what to do 

Offer test case for rvitals Power Supply Redundancy function.

The requirement from victor is:

I opened a pull request for Power Supply Redundancy field being empty today, I am wondering if we could have a rvitals test that checked the key/value pairs...  Something like this: `rvitals mid05tor12cn05 | awk -F':' '{print NF}' | grep -v 3` and if we have some fields come out, it would fail.  but this one doesn't work because it's using : and even when `<node>: PowerSupplyRedundancy: ` it does come out to 3 fields.. . but just thinking if there's a quick way to do attribute validation in  a single command testcase

**Comment by neo954** [comment]
@hu-weihua, FYI. It is great if you have time and can review the following pull request.
 
xcat2/xcat-core#5002
