### ISSUE TITLE
Add user name check into CI test

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#140]
What to do:

If user is using "root" account to commit pull request to github,  CI should throw out a error message when doing PR format check.

**Comment by hu-weihua** [comment]
@gurevichmark, could you help to achieve this task? thanks.

**Comment by gurevichmark** [comment]
@hu-weihua Since the PR is merged, can you close this issue ?

**Comment by hu-weihua** [comment]
Thanks @gurevichmark for all your help. I will close this issue.
