### ISSUE TITLE
Automated CORAL regression 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#15]
what to do:

Automated regression test against CORAL configuration.

ENV:  Os: pegas 1.1   DB: PostgreSQL   Node: p9vm (mn/sn)+witherspoon physical mathine (cn)  hierarchy:SN diskless (suppose it can not access public network), hardware control goes to python

* [x] hierarchy cluster setup -- use bundle, need to offer test case for sn diskless setup.
* [x] python package installation
* [x] 3 basic provisions against P9 physical machine in hierarchy cluster
* [x] hardware commands regression in hierarchy

**Comment by whowutwut** [comment]
@hu-weihua This is great.  Can we also document what the plan is for getting this automation in place.. what technology are we using.  Can it apply generically to any configuration OS/DB/node/SW?

**Comment by hu-weihua** [comment]
@whowutwut , the implementation almost all bases on current automation framework. Our current automation framework support any configuration OS/DB/node/SW, but do not support scaling cluster, just one MN, one SN and one CN.  

For this task, I need to enhance current framework a little, due to we need to support python package installation, some repo need to prepare ahead. But there is no new technology, just ``jenkins`` + ``xcatjktest script`` + ``xcattest script`` + ``case bundle``. 

I guess you care about weather this solution can be used in any environment, for example brigges01 cluster. From technical point of view, it can.  Just need correct configuration, `xcattest script`` can do all the job. In fact all the job of ``jenkins`` + ``xcatjktest script`` is to set correct configuration for ``xcattest script``. 

Maybe I can offer a document to describe how to use ``xcattest`` to achieve this solution in any cluster, list which attribute need to be set and how to set.  But the task of writing document will be planed behind this task. Because we do need a working regression environment for any build for CORAL, it is a little urgent.

**Comment by hu-weihua** [comment]
Have implemented automation project ``Pegas1.1-P9-PostgreSQL-CORAL``.
