### ISSUE TITLE
Build new release packages for goconserver

### ISSUE THREAD

**Issue by chenglch** [xcat2/xcat2-task-management#155]
- [x] Modify makefile and rpm/deb scripts to build goconserver with web pages
- [x] Setup etcd cluster
- [x] xcat certificate for goconserver cluster
- [x] Setup goconserver cluster with etcd and xCAT for UT and demo purpose, fix bugs if encountered.
- [x] Build and upload goconserver packages for different platforms (only on repo release link)

**Comment by zet809** [comment]
The x86_64 rpm package in https://github.com/xcat2/goconserver/releases v0.3.0 have been verified, so close this task.
