### ISSUE TITLE
Feature verify: HA cluster can work as expected

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#163]
what to do:

Verify new feature HA:

Now suppose the HA cluster has been set up.

* [x] Offer [test plan](https://github.com/xcat2/xcat-core/wiki/Function-Verification-Test-Design-of-xCAT-High-Availability) (include test case list )to verify a HA cluster can work correctly 
        Such as two nodes can switch when some accident happened,  if xcat basic command can work after switching and so on.
* [x] Finish test cases 
     

Depending on small group meeting, test need to include (but not limit) below scenario:

* [x] If xcat can work as expected after being installation by HA solution
* [x] If primary node can be switched to second node when hit accident
* [x] if xcat can work as expected after switching to second node
* [x] The data in xcat DB should be same in the 2 node after switching 
* [x] The time of 2 HA nodes should be consistent all the time

Reference #161 #160 #144 #137 #125 #126 

http://10.5.106.1/install/HA/xcat-core/docs/build/html/advanced/hamn/setup_ha_mgmt_node_with_shared_data_auto.html#setup-ha-mgmt-node-with-shared-data-auto

**Comment by neo954** [comment]
See https://github.com/xcat2/xcat-extensions/issues/10

**Comment by neo954** [comment]
See xcat2/xcat-extensions#26 for the test cases.

**Comment by zet809** [comment]
I think the task is finished, @neo954 , pls reply comments from @whowutwut in https://github.com/xcat2/xcat-extensions/pull/26, Thx!
