### ISSUE TITLE
Feature verify: HA cluster setup from 2 nodes with new os

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#166]
what to do:

* [x] Verify HA cluster setup script which sets up cluster from 2 new OS nodes.(It is better to offer a test case)

* [x] Run HA cluster basic function verification by cases generated in #163

**Comment by neo954** [comment]
See xcat2/xcat-extensions#10 xcat2/xcat-extensions#11 xcat2/xcat-extensions#13 xcat2/xcat-extensions#14 xcat2/xcat-extensions#17 xcat2/xcat-extensions#20 xcat2/xcat-extensions#21 xcat2/xcat-extensions#22 xcat2/xcat-extensions#23 xcat2/xcat-extensions#24 xcat2/xcat-extensions#25
