### ISSUE TITLE
Verify the HA best practice steps based on doc

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#167]
what to do:

* [x] Verify the HA best practice steps based on doc developer offered

The reference
[Use Case: CORAL system HA](https://github.ibm.com/vhu/c910env/issues/275)
https://github.ibm.com/vhu/c910env/issues/304

**Comment by hu-weihua** [comment]
Due to the development has been move to sprint 2, so move this task to sprint 2

**Comment by hu-weihua** [comment]
Hi, @neo954 , Developer has finished the document in http://xcat-docs.readthedocs.io/en/latest/references/coral/ha/index.html, could you start this task now? thanks

**Comment by neo954** [comment]
* [ ] Need to inform the document is RHEL7 only.
* [ ] Need to explain the difference among SQLite, MariaDB and PostgreSQL.

**Comment by neo954** [comment]
The documentation is already verified.
