### ISSUE TITLE
Test xcat-inventory cluster configuration templates

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#17]
what to do:

To test ``xcat-inventory`` cluster configuration templates.

The related link 

https://github.ibm.com/HPC-Next/xCAT-Incubator

**Comment by hu-weihua** [comment]
move this task to sprint 2.

**Comment by hu-weihua** [comment]
covered by other task, this is outdated. close it.

**Comment by zet809** [comment]
Covered by which one? @hu-weihua

**Comment by hu-weihua** [comment]
The related task is  #28
