### ISSUE TITLE
[HA]ntp support

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#176]
ntp support : Make sure the time on the primary management node and standby management node is synchronized.

**Comment by gurevichmark** [comment]
@bybai Is there a need to do this ? Can you think of some problems if two nodes are not time synchronized ?

**Comment by bybai** [comment]
All HA MN use the same DB in shared data directory. After we setup the first HA MN node, we configure new DB in shared data directory. When we setup second new HA MN, we install xcat and db rpms in OS first, then stop all services to create sym-link using shared data directory. If the second MN node clock is older than the clock in shared-data DB, starting DB using shared data directory will have problem.
Here I think we need to work around this scenario. 

I think we should make sure DB can start in second MN and then synchronize time.
The idea:
1. During deactivate process, before un-link directories, we can re-touch the /etc/xcat/ha_mn file. so that ha_mn file creation time in shared data directory should have latest date than that in database. 

2. During second HA MN node setup process, check the creation time of ha_mn, 
if the OS clock is latest than the creation time of ha_mn, the process can continue, after the DB service and xcat are started, we can find NTP server from xcat db, and can re-configure the time. 
If the OS clock is older than the creation time of ha_mn, should print error, and exit the setup process to let user adjust the OS clock.

3. During activate process, should have the similar check process.

**Comment by bybai** [comment]
That is fine.
