### ISSUE TITLE
[FVT] Add ubuntu 18.04 into daily regression system

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#188]
what to do:

Add ubuntu 18.04 into daily regression system after developer will have finished verification.

**Comment by neo954** [comment]
* [ ] Remove the test for Ubuntu 14.04.4 on x86-64
* [ ] Add test for Ubuntu 18.04 on x86-64 
* [ ] Add test for Ubuntu 18.04 on ppc64el

**Comment by neo954** [comment]
Currently, this task is blocked by issue xcat2/xcat-core#5306.
