### ISSUE TITLE
Feature verify : xcat-inventory osimage support environment variables(export part) 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#189]
What to do:

To verify xcat-inventory osimage support environment variables (export part).

* [ ] offer a [test plan](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-xcat-inventory-osimage-environment-variables-export-part) (including test case list)
* [ ] finish test case planned 
* [ ] finish test depending by test cases

Reference:
xcat2/xcat-inventory#46

**Comment by tingtli** [comment]
PR is https://github.com/xcat2/xcat-core/pull/5314

**Comment by hu-weihua** [comment]
@tingtli Could you pasted your test plan in [test plan](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-xcat-inventory-osimage-environment-variables-export-part), thanks
