### ISSUE TITLE
mlnx and cuda  new version verification

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#20]
what to do 

If there are new mlnx and cuda  release during xcat 2.14 sprint 1 time window, do regression test for new release.

**Comment by neo954** [comment]
The following pull request was committed.
 * xcat2/xcat-core#4979
 * xcat2/xcat-core#4980
 * xcat2/xcat-core#4990

**Comment by hu-weihua** [comment]
@neo954, could you offer a list about which version of CUDA or MLNX you have verified in this task? It will be helpful for CDL and POK team to collaborate with each other. Thanks.

**Comment by neo954** [comment]
@hu-weihua, The following packages was used.
```
-rw-r--r-- 1 root   root   1540855330 Mar 21 01:01 cuda-repo-rhel7-9-2-local-9.2.64-1.ppc64le.rpm
-rw-r--r-- 1 root   root        79844 Oct  8 22:31 dkms-2.4.0-1.20170926git959bd74.el7.noarch.rpm
-rw-r--r-- 1 nobody nobody  166526976 Mar  8 01:53 MLNX_OFED_LINUX-4.3-1.0.1.1-rhel7.5alternate-ppc64le.iso
-rw-r--r-- 2 nobody nobody 3338719232 Mar 14 04:29 RHEL-ALT-7.5-20180308.0-Server-ppc64le-dvd1.iso
```
