### ISSUE TITLE
Investigate how to operate github web page by Restapi 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#205]
What to do:

* [ ] Investigate the Restapi of github
* [ ] Prepare a demo programs to modify the web page of  github

Need to achieve below operations by restapi of github
* [Tag the Release on GitHub Web Page](https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/Release_process.md#71-tag-the-release-on-github-web-page)
* Edit the sidebar ``News`` in [the Wiki on xCAT github](https://github.com/xcat2/xcat-core/wiki), to add a new entry for current release.

**Comment by hu-weihua** [comment]
Can not finish in 2.14.2 sprint2, move to 2.14.3 sprint 1.

**Comment by xuweibj** [comment]
* Edit sidebar ``News``
1. ``git clone https://github.com/xcat2/xcat-core.wiki.git``
2. Modify test_sidebar.md file to add new entry for current release
3. ``git add/commit/push``
