### ISSUE TITLE
Using xcatha.py in postscripts to automaticly install MN HA on virtual VM

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#221]
https://github.ibm.com/vhu/c910env/issues/301

This task only focus on setup HA in postscripts
- Install xCAT (From online or 1st MN's xcat repo)
- Setup postgresql
- Using an existing shared storage (/xcat/HA/<hostname -s>)

User can use this postscript to create one primary MN,  or both active and standby MNs.

**Comment by bybai** [comment]
Use ``xcatha.py`` easily re-create the HA environment base steps:

xCAT MN is c910f03c17k13
compute node c910f03c17k14 and  c910f03c17k15 will be configured as HA standby MN
VIP is 10.3.17.50
VIP hostname is hamn
Shared data directory is /HA
VIP alias NIC is  eth1:0

1. download xcatha.py into /install/postscripts on xCAT MN c910f03c17k13
```
cd /install/postscripts
wget https://raw.githubusercontent.com/xcat2/xcat-extensions/master/HA/xcatha.py
```
2. touch script cfg_hamn, and configure it based on specific  variables in /install/postscripts on xCAT MN xcatmn:
```
vim cfg_hamn
!/bin/bash
NFS_SERVER=10.3.17.13
SHARE_DATA=/HA
VIP=10.3.17.50
VIP_hostname=hamn
NIC=eth1:0

mkdir -p $SHARE_DATA
mount $NFS_SERVER:/$SHARE_DATA /$SHARE_DATA
python xcatha.py -s -p /$SHARE_DATA -v $VIP -i $NIC -n $VIP_hostname
```
3. add "confignetwork -s,cfg_hamn" into c910f03c17k14 and c910f03c17k15 postbootscripts, since c910f03c17k14 and c910f03c17k15 use the same shared data directory and VIP, they cannot be provisoned at the same time, they should be provisioned one after another
```
chdef <node> -p postbootscripts="confignetwork -s,cfg_hamn"
rinstall  <node> osimage=rhels7.4-ppc64le-install-compute
```
4. login standby HA MN , activate it as the primary MN
```
python /xcatpost/xcatha.py -a -p /HA -v 10.3.17.50 -i eth1:0 -n hamn -m 255.0.0.0
```
5. login primary HA MN, deactivate the primary MN
```
python /xcatpost/xcatha.py -d -v 10.3.17.50 -i eth1:0
```

**Comment by zet809** [comment]
hi, @bybai , seem the task is done, shall we close it?

**Comment by bybai** [comment]
Yes
