### ISSUE TITLE
the build framework

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#233]
As a FVT or dev, I need to build a special verison and arch for xcat-core, trigger it from Jenkins
* [x] investigate triggering the build project from Jenkins ==> 3
* [x] docker file + docker run command to do the build  ==> 2  (https://github.ibm.com/xcat2/jenkins/pull/166)

**Comment by immarvin** [comment]
the previous work https://github.com/immarvin/xcat-docker/tree/master/build

**Comment by xuweibj** [comment]
Jenkins with GitHub:

1. Install and configure Jenkins
2. Install "build with parameters & git parameter" from Manage Plugins
3. Create new project with settings as below:
    * Name: BRANCH
    * Parameter Type: Branch
    * Git 
        * Repositories: repo URL
        * Branches to build: Branch Specifier (blank for 'any'): $BRANCH
4.  Build with Parameters to choose branch to build

**Comment by robin2008** [comment]
Dockerfile is ready in https://github.ibm.com/xcat2/jenkins/pull/166

**Comment by zet809** [comment]
Replaced by #253 , so close this one.
