### ISSUE TITLE
Setup more p9vm nodes in f6u13

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#26]
what to do:

Setup more VM nodes in f6u13, using Non-host disk to get better performance.

Please do this task ASAP, thanks

**Comment by zet809** [comment]
Thx @hu-weihua , maybe it is a good chance to update our document to use lvm.

**Comment by whowutwut** [comment]
@hu-weihua @neo954 What have we found if leveraging NVMe for storage of VMs, 
Is there any progress on this task that can be documented here for the benefit of the team. 

What was done to partition it, what is done to target this NVMe drive?  This goes from New to Review without any info at all to benefit more folks who may be interested to know how to leverage NVMe by use of xCAT..

**Comment by hu-weihua** [comment]
@whowutwut, FVT needed 9 nodes for automation test, so we tried to create some VMs in f6u13. At first, we used  ``qcow2 file on SATA disk + virtio vm nic model`` configuration to create VMs,  we found the performance of these VMs were very low, a regular rhels7.5 regression test could not be finished in 10 hours. Then we tried to change ``virtio vm nic model`` to ``virtio-net-pci vm nic model``, it became better, but the improvement was not significant. Then @neo954 tried to use ``LVM on NVMe disk + virtio-net-pci vm nic model`` configuration to recreate VMs, this time, the performance is improved significantly, the same rhels7.5 regression test can be finished in 6 hours. 

@neo954, could you offer detailed steps about how to achieve this? thanks.
