### ISSUE TITLE
 Manual test against xcat-inventory user cases in RTC document

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#28]
What to do:

The reference document is [xcat-inverntory man page](http://xcat-docs.readthedocs.io/en/latest/advanced/xcat-inventory/index.html?highlight=xcat-inventory)

* [x]  offer [Test Design of xcat-inventory user case](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-xcat-inventory-user-case)

* [x] finish test depending on the design

**Comment by xuweibj** [comment]
Test record:

* "flat_cluster_template.yaml" test

* [ ] Init test
Create "init.yaml" file to create 3 nodes, one is "OpenBMC controlled Power server", one is "IPMI controlled Power server" and one "x86_64 server".
Import "init.yaml" file and export to “test.yaml” file and check difference with diff.

* [ ] Modify table content
Modify “passwd”, “site” table data in initial file, and import without “-c”
Export new yaml file and diff to check

* [ ] Add new node
 Add new one node to initial file, and import without “-c”
Export yaml file and diff to check

* [ ] Delete node
Delete one node to initial file, and import with “-c”
Export yaml file and diff to check.

* "flat_kvm_cluster_template.yaml" test

* [ ] Init test
Create Create "init.yaml" file to create 2 nodes, PowerKVM based VM and KVM based X86_64 VM.
Import "init.yaml" file and export to “test.yaml” file and check difference with diff.



If there is attribute defined in initial data but not in “test.yaml”, check nodes definition or table.

**Comment by hu-weihua** [comment]
Covered original task #17
