### ISSUE TITLE
Test xcat-inventory export/import performance in larger cluster environment

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#29]
What to do:

* [x] offer [test Design of xcat inventory export import performance](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-xcat-inventory-export-import-performance)

* [x] finish test depending on above test plan.

**Comment by xuweibj** [comment]
Test record:

* Scenario 1: -- Export & import different numbers' node

number of attributes: 20

nodes ----- export ----- import 
 100 ------ 0m2.567s ---- 0m8.328s
 200 ------ 0m4.365s --- 0m15.556s
 500 ------ 0m9.571s ---- 0m37.667s
 1000 ----- 0m18.283s --- 1m15.868s
 2000 ----- 0m36.388s -- 2m38.961s
 5000 ----- 1m33.069s --- 7m33.550s
10000 ---- 3m20.774s -- 17m45.630s
