### ISSUE TITLE
investigate sle15 diskful and diskless CN provision support 

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#290]
Investigate sles15 diskful and diskless CN provision support 
* [x] ppc64le
* [x] x86_64

**Comment by bybai** [comment]
Investigate results:
The following 3 parts need to be enhanced for sle15 diskful CN provision support:
1. copycds should be enhanced:
    #. support osname sle (for sle15) and sles (sles12.3 below) https://github.com/xcat2/xcat-core/issues/5614
    #. missing arch for ppc64le osimage definition on ppc64le https://github.com/xcat2/xcat-core/issues/5615
2. enhance pkglist support:
    sle15 separate installer and packages into different ISO. All packages are separated into different products in packages ISO, here needs scripts to support register different package product and use different packages from different product. 
3. postscripts failure: the deployment status is postbooting.

**Comment by bybai** [comment]
Investigate results for sle15 diskless CN provision support, the follwing issues should be fixed at least:
1. `genimage` failed for missing creating package repo in sle15 : https://github.com/xcat2/xcat-core/issues/5616

2. pkglist support:
    1. With SLE 15, `dmraid` is considered deprecated. It will be removed in a future service pack. Instead of `dmraid`, use `mdadm`. 
    2. `ntpd` is replaced by `chrony`.

3. In rootimg, `etc/passwd` is empty, cause 121 packages installed failed, after adding "root:x:0:0:root:/root:/bin/sh" in /etc/passwd, this error can be fixed, and `genimage` can finished.

4. After diskless node netbooting, I hit this error: " vim: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory"

5. `/etc/init.d/xcatpostinit` is not ran during netbooting diskless system. After I copied and configured xcatpostinit1.service in diskless rootimg, `xcatpostinit1.service` failed during netbooting, I can see the follwing error from screen:
```
xcatpostinit1.service is missing 
[  OK  ] Reached target Network.
         Starting Login and scanning of iSCSI devices...
         Starting xcat service on compute no…otscript and update node status...
[  OK  ] Started Login and scanning of iSCSI devices.
none:/root # systemctl xcatpostinit1.service start
Unknown operation xcatpostinit1.service.
none:/root # ls /opt/xcat/xcatpostinit1
/opt/xcat/xcatpostinit1
```

**Comment by jjohnson42** [comment]
FYI, lenovobuild2.14 has working sle15 support...

I made a pull request for the diskful support.

I can try to cherry pick the stateless changes for review..

**Comment by bybai** [comment]
@jjohnson42,
I merged your PR for diskful support https://github.com/xcat2/xcat-core/pull/5470, it is valuable for us, I tried it on x86_64 systems, it almost works. But it needs to be enhanced since XCAT support ppc64le and compatibility of sles12.3 etc as I mentioned in above comments. We also looking forward to your new PR for stateless changes. Thanks.

**Comment by jjohnson42** [comment]
I'll try to do that again.

The biggest puzzle for me with SLE15 was how to handle the multi-edition media, so hopefully this clarifies a lot for the ppc64le edition as well.
