### ISSUE TITLE
leverage osimage+ansible to setup powerAI enterprise environment

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat2-task-management#299]
* [x] preparing the repos        \
* [x] preparing the osimages   |--> #276  
* [x] deploy/ update on CN  ==> #352

**Comment by neo954** [comment]
* A design document of hierarchical directory structure to put all PowerAi softwares in the `/install/REPO` directory.
* A tool to help end user to put all PowerAi related packages into `/install/REPO`, based on the design above.
* Create a working osimage definition
* A framework to let the end user to add their own scripts to do additional customize.

**Comment by zet809** [comment]
Covered by #276 + #352 , so close this task.
