### ISSUE TITLE
[HPC-devops] investigation building container based osimage inventory and facilite to install ICP

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#300]
* [x] verifying ICP installation on power system
* [x] The osimage to setup docker host
* [x] deploy ICP image onto docker host

**Comment by zet809** [comment]
Reference: https://github.ibm.com/hpc-devops/xcat_clusters/pull/182

**Comment by zet809** [comment]
* [x] diskless image to setup docker host, apply docker image + setup ICP master:
    What have done:
    * verification shows that some of ICP master service(hung at MariaDB) can not be start successfully on diskless host
    * ICP docker image tar ball is 9.xG, it is impossible to insert in a diskless image.
    * diskless host can be started with worker images
    So, normal diskless image+docker is the only value can add to ICP installation
