### ISSUE TITLE
cuda and mlnx regression 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#318]
what to do：

* [x] do cuda and mlnx regression on p9 physical machine and pegas1.2

**Comment by zet809** [comment]
Pls notice to make sure we have document for cuda install on p9, and makesure it is correct. No kernel error when diskless or diskful OS is booted up.

**Comment by neo954** [comment]
Tested with CUDA 9.2 and MLNX_OFED 4.4 on RHEL 7.5 and RHEL 7.5-alt on ppc64le.
```
cuda-repo-rhel7-9-2-local-9.2.148-1.ppc64le.rpm
cuda-repo-rhel7-9-2-148-local-patch-1-1.0-1.ppc64le.rpm
MLNX_OFED_LINUX-4.4-2.0.7.0-rhel7.5-ppc64le.iso
MLNX_OFED_LINUX-4.4-2.0.7.0-rhel7.5alternate-ppc64le.iso
```

**Comment by neo954** [comment]
Will close this one.
