### ISSUE TITLE
Try to run xcat-inventory on automation control node to verify its usability

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#33]
what to do:

Treat automation control node as a real customer, try ``xcat-inventory`` against it, to verify its usability.

**Comment by bybai** [comment]
1, Tested migrate xCAT autotest control node c910f02c04p24 to new xCAT MN bybc0605.
2, Summarized the whole test process and finished doc as https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/How_to_Migrate_Control_Node.rst
