### ISSUE TITLE
add labels for cases without labels

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#341]
what to do:

* [ ] add labels for cases without labels

* [ ] update labels depending on the result of https://github.com/xcat2/xcat2-task-management/issues/340

**Comment by tingtli** [comment]
https://github.com/xcat2/xcat-core/pull/5763

**Comment by hu-weihua** [comment]
Have not finished in sprint 1, move to sprint 2. need one more day to handle this task in sprint 2.
