### ISSUE TITLE
The checklist for Early Drop build 

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#35]
For functions:
1. openbmc support: Mixed cluster, some node hwctl from MN, some from diskless SN
    1. multiple nodes verification
    2. hierarchical hwctl
    3. xCAT-openbmc-py installation, updating
        1. the step is correct in RTD?
        2. For diskless SN, re-geimage?
    4. the openbmcperl to control which command go through perl
2. goconserver: MN + diskless SN + at least 2 CN(1 P9 VM, 1 Witherspoon Node)
    1. package installation/updating for MN+SN
    2. conserver switch to gocons
        1. MN+SN switch to gocons
        2. the gocons configuration keep after updating
        3. gocons configuration keep after reboot diskless SN
    3. For diskless SN with configuration below:
        1.  the scenario below:
            1. If not set setupconserver
            2. If setupconserver set to 1
            3. If setupconserver set to 2
        2. test:
            1. what happened to run makegocons?
            2. whether the configuration keep after reboot SN?
            3. If not for step2 above, how to recover?
3. xcatinventory
    1. whether update/install will break backup/restore
    2. the user case document verification, 
    3. installation document verification
4. ondiscover
    1. document?
    2. work with hardware discovery?
5. OS support:
    1. Pegas1.1 (Apr 3rd GA)
    2. RHV4.2 (March 12 RC, Apr 17 GA) ==> We can verify after Early Drop build ship
    3. RHEL 7.5 (Apr 3rd GA)

General functions:
* ​xCAT updating
* bmcdiscover
* xCAT tunneling document
    * arp cache
    * xcatmaxconnections, xcatmaxbatchconnections
    * ulimit
    * …
* cuda, mlnx

**Comment by hu-weihua** [comment]
Have been covered by release cycle, thanks @zet809
