### ISSUE TITLE
Run 'discovery' regression against April 6 build

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#37]
what to do:

Run 'discovery' regression against April 6 build.

* [x] [bmcdiscover](https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/bmcdiscover_manual_test_steps.md)
* [x] [Switch Based Node discovery ](https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/Switch_Based_Node_discovery_Manual_Test_Steps.md)
* [x] [MTMS Based Node discovery](https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/MTMS_Based_Node_discovery_Manual_Test_Steps.md)
* [x] [Switch Based Switch discovery](https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/Switch_Based_Switch_discovery_Manual_Test_Steps.md)

**Comment by chenglch** [comment]
@hu-weihua , Could you help add some itmes about goconserver testing while running discovery? Some problem encountered in Big data solution and I haven't got a chance to look into their environment.

From victor:
Interesting thing happened with goconserver. We're getting hits in elastic now, but they're all from the xcat genesis, normal console stuff still doesn't hit.

To verify this issue, `elastic` is not needed, just to see is there any console output( or from /var/log/consoles/) after genesis. I guess the user name or password is not refreshed at `goconserver` side after discovery.

**Comment by xuweibj** [comment]
Test record:

* bmcdiscover

 bmcdiscover --range switchip
```
# bmcdiscover --range 172.11.205.12
Warning: No bmc found.
```
bmcdiscover --range hostip
```
# bmcdiscover --range 172.12.139.5
Warning: No bmc found.
```
bmcdiscover --range hmcip
```
# bmcdiscover --range 10.0.0.201
Warning: No bmc found.
```
bmcdiscover --range pduip
```
# bmcdiscover --range 172.21.253.105
Warning: No bmc found.
```

**Comment by chenglch** [comment]
xCAT updated the SSL certificate but goconserver is still use the old one. So restarting goconserver solve the issue mentioned above.

**Comment by xuweibj** [comment]
Use ``makegocons`` in the whole test. Did not encounter question during "discovery", "genesis".
