### ISSUE TITLE
xCAT REST API that returns output similar to nodels range command 

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#38]
This is divided from https://github.com/xcat2/xcat-core/issues/5031
It would be useful for the CORAL customers to have a REST API with a more compact output similar to the nodels command, where just a list of nodes is returned.

the `https://bybc0602.cluster.com/xcatws/nodes` returns all nodes.
What they want is send a noderange and get back a list of nodes matching that range:
`https://briggs01/xcatws/nodes/mid05tor12cn15+1/nodels`
OR
`https://briggs01/xcatws/nodes/mid05tor12cn[15-20]/nodels`
OR
`https://briggs01/xcatws/nodes/mid05tor12cn15,mid05tor12cn16,mid05tor12cn17/nodels`
OR
`https://briggs01/xcatws/nodes/<group>/nodels`

Our REST API seems to support noderange but only if you ask for attributes or some other things. I could not find API call that just returns a list of nodes in the range.

**Comment by gurevichmark** [comment]
@bybai Why open this separate "xcat2-task-management" issue.
Why not continue to track it under the xcat2/xcat-core#5031

**Comment by bybai** [comment]
Hi @gurevichmark xcat2/xcat-core#5031  contains 2 different issues and 1 investigate, so I break down it as separate one for agile.
