### ISSUE TITLE
[RH8] Make configeth(confignetwork) ethernet works on RHEL 8

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat2-task-management#399]
confignetwork call configeth to configure ethernet NIC. 
* [x] Configure a standalone ethernet install NIC
* [x] Configure static secondary NIC

**Comment by neo954** [comment]
Hello @bybai,

Please check the latest fail log of Jenkins autotest log in https://github.com/xcat2/xcat2-task-management/issues/391#issuecomment-452609016

Good luck.

**Comment by bybai** [comment]
The investigate results:
In redhat8, should use "nmcli" to generate "ifcfg-*" files, and configure it as static ip.
The following are  Ethernet results: 
1. check the device status:
```
nmcli device
```
2. add a device:
```
nmcli connection add con-name ens4 ifname ens4 autoconnect no type ethernet ipv4.method manual ipv4.addresses 12.1.0.100/16
nmcli device connect ens4
```
3. modify a device:
```
nmcli con mod "ens4" ipv4.method manual ipv4.addresses 12.1.0.100/1
```
