### ISSUE TITLE
List interface of redfish related with xcat commands

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#442]
rbeacon
rpower
rsetboot
rinv
rvitals
reventlog
rspconfig
reventlog

**Comment by xuweibj** [comment]
Based 2 boston machine with different version

* login
``/redfish/v1/SessionService/Sessions``

* rpower
chassis: ``/redfish/v1/Chassis/[Backplane|Planar]``
compute: ``/redfish/v1/Systems/Computer``
bmc: ``/redfish/v1/Managers/BMC``

* rsetboot
``/redfish/v1/Systems/Computer``

* rspconfig
``/redfish/v1/Managers/BMC/EthernetInterfaces/1``
``/redfish/v1/Managers/BMC/NetworkProtocol``
``/redfish/v1/Chassis/Backplane/Power``

* rinv
``/redfish/v1/Chassis/[Planar|Backplane]``
``/redfish/v1/Chassis/Planar/Assembly``
``/redfish/v1/Systems/Computer``

* rvitals
``/redfish/v1/Chassis/Backplane/Thermal``
``/redfish/v1/Chassis/Backplane/Power``

* beacon
``/redfish/v1/Chassis/[Planar|Backplane]``
``/redfish/v1/Systems/Computer``

* reventlog
``/redfish/v1/Managers/BMC/LogServices/Log/Entries``
clear: ``/redfish/v1/Managers/BMC/LogServices/Log``

* rflash
``/redfish/v1/UpdateService/FirmwareInventory``
``/redfish/v1/UpdateService/FirmwareInventory/BMC``
``/redfish/v1/UpdateService/FirmwareInventory/PNOR``

**Comment by zet809** [comment]
* rspconfig GET
    * [x] bmc mac addr: *MAC* in /redfish/v1/Managers/BMC/EthernetInterfaces/1
    * [x] vlanid: *VLAN.VLANId* in /redfish/v1/Managers/BMC/EthernetInterfaces/1
    * [x] hostname: *HostName* in /redfish/v1/Managers/BMC/EthernetInterfaces/1
    * [x] ipv4: *IPv4Addresses[0].{Address|SubnetMask|AddressOrigin|Gateway}* in /redfish/v1/Managers/BMC/EthernetInterfaces/1
    * [x] nameserver:  *NameServers* in /redfish/v1/Managers/BMC/EthernetInterfaces/1
    * [x] ntp server: *NTP.NTPServers* in /redfish/v1/Managers/BMC/NetworkProtocol
    * [ ] powerrestorepolicy
    * [ ] powersupplyredundancy
    * [ ] timesyncmethod
    * [ ] bootmode
    * [ ] autoreboot 
* rspconfig SET
    * [ ] admin_passwd
    * [ ] hostname
    * [ ] ntpservers
    * [ ] sshcfg
    * [ ] powerrestorepolicy
    * [ ] powersupplyredundancy
    * [ ] timesyncmethod
    * [ ] bootmode
    * [ ] autoreboot

**Comment by zet809** [comment]
hi, @whowutwut , here are some detailed information about xCAT command and Redfish interface mapping, there are still some question mark and @xuweibj need to check with firmware team.
