### ISSUE TITLE
Go through current status of all xcat-inventory cases

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#461]
what to do:

* [x] Do regression of all xcat-inventory cases in rhels and ubuntu

* [x] Do regression of all inventory_ci cases in ci

* [x] To make sure if there is any cases should be added ``inventory_ci`` label. If there are, add label and make sure them can run in CI environment. 

Resolve the problems encountered.

**Comment by tingtli** [comment]
here is the result for regression of rhels

[xcattest.log.20181212003427.log](https://github.com/xcat2/xcat2-task-management/files/2701893/xcattest.log.20181212003427.log)
