### ISSUE TITLE
[xcat-inventory]refine and merge PR on git backend 

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat2-task-management#494]
* [x] refine, resolve conflicts and merge PR https://github.com/xcat2/xcat-inventory/pull/115
* [ ] fix issue https://github.com/xcat2/xcat-inventory/issues/141
* [ ] provide doc for xcat-inventory features on inventory source control

**Comment by zet809** [comment]
[ ] UT cases

**Comment by zet809** [comment]
hi, @immarvin , is this EPIC finished? If so, pls close. Thx!
