### ISSUE TITLE
enhance current jenkintest script to support using container for regression testing

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#530]
As we publish a xcat container into docker hub, use this to install a xCAT MN and finish the regression test need some enhancement on current jenkins helper scripts.

After some initial investigation, most of the things need to be done in
```
<xcat2/jenkins >/xcatjktest
<xcat2/jenkins >/slave/test.sh
```

We need a new ENV variable `XCAT_TEST_DOCKERIMAGE` for specify the image tag, for example `xcat/xcat:latest`

if this variable is used, then ignore `XCAT_TEST_CORE` and `XCAT_TEST_DEP` as we use docker image to setup xCAT MN. So when run `xcatjktest` it needs to do:
- install docker-ce
- pull the `docker pull ${XCAT_TEST_DOCKERIMAGE}`
- run it with host network, something like below
```
docker run -d --name xcatmn --network=host --hostname xcatmn --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro xcat
```
- install xcat-test
- run test

Note:  
- if you need extra logs from container,  using more `-v` to specify the directory.
- if you want to run commands in xcat container from container,  you need to use `xdsh $mn docker exec $containername commands`

**Comment by robin2008** [comment]
Using `docker pull robin2008/xcat-ppc64le:2.14.5` for testing @hu-weihua

**Comment by hu-weihua** [comment]
The issues hit:

* [ ] Cannot communicate via libvirt to kvm nodes in docker container

* [ ] ``xcatmn.pok.stglabs.ibm.com exist either in /etc/hosts`` when run makedns in docker container

* [ ] copycds failed in docker container

```
RUN:copycds /RHEL-7.6-Server-ppc64le-dvd1-stable.iso [Thu Dec 20 14:05:43 2018]
ElapsedTime:1 sec
RETURN rc = 1
OUTPUT:
Error: [xcatmn]: copycds was unable to mount /RHEL-7.6-Server-ppc64le-dvd1-stable.iso to /var/run/xcat/mountpoint/594f6d1901cded47a372a367422fa0ef.
```

* [ ] it is strange, ``/val/log/xcat/`` is empty when get out of docker container.

*  link docker host's directory ``/var/log/dockercontainerlog``  to docker container's directory ``/var/log``.
```
#docker run -d --name xcatmn --network=host --hostname xcatmn --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v /opt/xcat/share/xcat/tools/autotest/:/opt/xcat/share/xcat/tools/autotest/ -v /tmp/automation_mountpoint:/tmp/automation_mountpoint -v /etc/hosts:/etc/hosts -v /RHEL-7.6-Server-ppc64le-dvd1-stable.iso:/RHEL-7.6-Server-ppc64le-dvd1-stable.iso -v /var/log/dockercontainerlog:/var/log -v /xCAT-test-2.14.6-snap201812190618.noarch.rpm:/xCAT-test-2.14.6-snap201812190618.noarch.rpm robin2008/xcat-ppc64le:2.14.5
```
* there are content in docker container's directory ``/var/log/xcat``, the directory ``/var/log/dockercontainerlog/xcat`` in docker host is empty.  But the content in ``/var/log/consoles`` in docker container are transfered out to  ``/var/log/dockercontainerlog/consoles`` in docker host

**Comment by hu-weihua** [comment]
**[INFO]**

* test project in automation development env: http://10.2.4.25:8080/view/hwh/job/docker-rhels7-ppcle/

* source code saved in ibm github ``https://github.ibm.com/xcat2/jenkins_dev/`` branch ``auto_docker_support``

**Comment by robin2008** [comment]
Ok, I'll take over the rest.  Thanks, mark it as done, using test driven for following.

**Comment by robin2008** [comment]
```
mount -o loop /RHEL-7.6-Server-ppc64le-dvd1-stable.iso /var/run/xcat/mountpoint/594f6d1901cded47a372a367422fa0ef
mount: /RHEL-7.6-Server-ppc64le-dvd1-stable.iso: failed to setup loop device: No such file or directory
```
This cause the `copycds` failed.

For `rpower` issue, need to use the /root/.ssh on host and set `echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config` in container.

**Comment by robin2008** [comment]
Found httpd is not running,  and it is caused by no `/var/log/httpd` directory.  Fix it in https://github.ibm.com/xcat2/jenkins_dev/commit/29fd1d9f5d2cbf43d9e6df62ddfb3b092e04a892

**Comment by robin2008** [comment]
Get the below test result when using below bundle
```
declare -a bundle=(
INCLUDE:rhels7.4_ppc64le.bundle
)
```

```

Failed cases: go_xcat_noinput, confignetwork_s_installnic_secondarynic_updatenode, confignetwork_secondarynic_updatenode, confignetwork_secondarynic_nicaliases_updatenode, confignetwork_secondarynic_nicextraparams_updatenode, confignetwork_secondarynic_thirdnic_multiplevalue_updatenode, addkit_kit, addkit_i, addkit_multikit, addkit_p, addkitcomp_i, addkitcomp_f, buildkit_cleanrepo_all, buildkit_buildtar, chkkitcomp_V, lskit_F, lskit_K, lskit_R, lskit_C, lskitcomp_C, lskitcomp_S, lskitdeployparam_k_1, lskitdeployparam_c_1, rmkit_t_no, rmkit_t_yes, rmkit_f, rmkit_V, nodeset_shell_incorrectmasterip, makedns_n, makedns, psh_i, updatenode_postscripts_loginfo, confignetwork_2eth_bridge_br0, confignetwork_2eth_bridge_br22_br33, confignetwork_bond_eth2_eth3, confignetwork_installnic_2eth_bridge_br22_br33, confignetwork_vlan_bond, confignetwork_vlan_eth0, encrypted_passwd_openssl_diskfull, confignetwork_vlan_false, nodeset_shell, reg_linux_statelite_installation_flat, SN_setup_case, reg_linux_diskfull_installation_hierarchy, reg_linux_diskless_installation_hierarchy, reg_linux_statelite_installation_hierarchy_by_ramdisk, reg_linux_statelite_installation_hierarchy_by_nfs, nodeset_disjointdhcps_petitboot, redhat_migration1, redhat_migration2, 
```
