### ISSUE TITLE
investigate code logic to add URL in confluent

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#532]
* [x] access xcat database
* [x] do nodelist through RESTful in confluent

**Comment by jjohnson42** [comment]
I don't quite understand, lsdef would be /noderange/<noderange>/attributes/

The confluent data structure is more natively 'objdef'-like.

**Comment by zet809** [comment]
Create the PR https://github.com/xcat2/confluent/pull/103 to add /xcat for confluent.
Hi, @jjohnson42 , will you pls help to review whether it is correct logic to add new url? Thx a lot!
