### ISSUE TITLE
[xcat-ansible] setup a xCAT cluster using xcat-inventory templates with ansible

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#55]
As a user, with xcat inventory config template and playbooks get from xcat.org, how to finish the xCAT installation in 5 minutes for both FLAT and Hierarchy network with small changes based on document
* reference https://github.com/chenglch/xcat-play

**Comment by whowutwut** [comment]
I’ve already completed this task

**Comment by bybai** [comment]
Hi @whowutwut and @zet809, 
We want to install xCAT with Ansible and use xcat-inventory templates in Ansible to easily setup a xCAT cluster in this task. Victor has completed xCAT installation with Ansible in  https://github.ibm.com/vhu/c910env/tree/master/ansible/management. Another part using xcat-inventory templates and playbooks to setup a xCAT cluster is not completed, so the title of this task will be changed to "setup a xCAT cluster using xcat-inventory templates with ansible" to continue uncompleted part.

**Comment by bybai** [comment]
1. Use ansible playbooks to sutup a xCAT cluster including:
   
    a. download xCAT and install xCAT
    b. configure xCAT MN (site, passwd,networks)
    c. define and customize OS image
    d. define compute nodes

2. Gaps among Victor's playbooks and above works:

    Victor have completed xCAT installation and OS image customization, configuring xCAT MN and defining osimage mainly using `chdef` command.  Now, we decide to use `xcat-inventory` templates and `xcat-inventory` commands to replace `chdef` in playbooks to realize xCAT MN configuration and compute nodes definition.  OS image customization part will be planned after xcat-inventory osimage support  is finished in the future.  

3. The scope of this task:

     * [ ] summarize the use case to setup a xCAT cluster using xcat-inventory templates
     * [ ] use xcat-inventory templates to configure xCAT MN with ansible
     * [ ] use xcat-inventory templates to define compute nodes with ansible
     * [ ] automate the whole use case with ansible

**Comment by bybai** [comment]
the mini-design https://github.com/xcat2/xcat-core/wiki/The-draft-mini-design-of-using-xcat-inventory-templates-to-setup-xCAT-cluster-with-ansible

**Comment by bybai** [comment]
Demo this task to China team, refinements TODOs in future sprint:
1. divide fast_cluster.yaml as configure_cluster.yaml and fast_cluster.yaml, all variables put into configure_cluster.yaml
2. Investigate multiple iso paths in a list in configure_cluster.yaml
3. Print summary information when the playbook is completed
4. Add variable for setting up flat cluster or hierarchy cluster in configure_cluster.yaml
5. Investigate transfer input parameters to ansible-playbook
6. Investigate how to run independent role separately, for example, if only running customize osimage
7. Node/osimage/network.service/provision management function will be in future task to realize
8. Considering use xcat-inventory osimage part to replace current osimage solution

Close this task for prototype.
