### ISSUE TITLE
Investigate witherspoon redfish interface

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#553]
* [x] Choose 1 witherspoon machine to update firmware with redfish support ---- Mark
* [x] Investigate witherspoon interface of redfish
    * [x] login
    * [x] rpower
    * [x] rsetboot
    * [x] rinv
    * [x] rvitals
    * [x] rbeacon
    * [x] rspconfig
    * [x] rflash

**Comment by gurevichmark** [comment]
Downloaded BMC firmware from `https://openpower.xyz/job/openbmc-build/distro=ubuntu,label=builder,target=witherspoon/lastStableBuild/` into `/xcat/iso/firmware/ibm/openpower_redfish/`

**Comment by gurevichmark** [comment]
Flashed `f5u16` with RedFish BMC firmware:
```
[root@stratton01 openpower_redfish]# rflash f5u16 -l
f5u16: ID       Purpose State      Version
f5u16: -------------------------------------------------------
f5u16: 78d09908 BMC     Active     ibm-v2.0-0-r44-0-g843c2e1
f5u16: b04fff27 BMC     Active(*)  ibm-v2.0-0-r46-0-gbed584c
f5u16: e339c76d Host    Active     IBM-witherspoon-ibm-OP9_v1.19_1.189
f5u16: 33029bc1 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.192
f5u16: c3804a0c BMC     Active(+)  v2.4-248-ga5c52ff
f5u16:

[root@stratton01 openpower_redfish]# rpower f5u16 bmcreboot
f5u16: Firmware will be flashed on reboot, deleting all BMC diagnostics...
f5u16: BMC reboot

[root@stratton01 openpower_redfish]# rflash f5u16 -l
f5u16: ID       Purpose State      Version
f5u16: -------------------------------------------------------
f5u16: b04fff27 BMC     Active     ibm-v2.0-0-r46-0-gbed584c
f5u16: c3804a0c BMC     Active(*)  v2.4-248-ga5c52ff
f5u16: e339c76d Host    Active     IBM-witherspoon-ibm-OP9_v1.19_1.189
f5u16: 33029bc1 Host    Active(*)  IBM-witherspoon-ibm-OP9_v1.19_1.192
f5u16:
[root@stratton01 openpower_redfish]#
```

**Comment by xuweibj** [comment]
**rpower** 

* on/off/reset/boot ``/redfish/v1/Systems/motherboard``
```
"Actions": {
    "#ComputerSystem.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "On",
        "ForceOff",
        "GracefulRestart",
        "GracefulShutdown"
      ],
      "target": "/redfish/v1/Systems/motherboard/Actions/ComputerSystem.Reset"
    }
```
* state
```
/redfish/v1/Chassis/motherboard  ---------------?
/redfish/v1/Chassis/system    ------------------?

"PowerState": "On",
/redfish/v1/Systems/motherboard
"PowerState": "Off",
```

* bmcreboot ``/redfish/v1/Managers/bmc``
```
"Actions": {
    "#Manager.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "GracefulRestart"
      ],
      "target": "/redfish/v1/Managers/bmc/Actions/Manager.Reset"
    }
  },
```
* bmcstate ``/redfish/v1/Managers/bmc``
```
"PowerState": "On",
```

**Comment by gurevichmark** [comment]
Simple Unit Test scripts to verify support: https://github.ibm.com/vhu/c910env/issues/462

**Comment by gurevichmark** [comment]
Noticed some differences between Supermicro and Witherspoon implementation for firmware inventory:
Witherspoon:
```
curl  -X GET https://10.5.16.101/redfish/v1/UpdateService/FirmwareInventory/{ID}

{
  "@odata.context": "/redfish/v1/$metadata#SoftwareInventory.SoftwareInventory",
  "@odata.id": "/redfish/v1/UpdateService/FirmwareInventory/b04fff27",
  "@odata.type": "#SoftwareInventory.v1_1_0.SoftwareInventory",
  "Id": "b04fff27",
  "Name": "Software Inventory",
  "Status": {
    "Health": "OK",
    "HealthRollup": "OK",
    "State": "Enabled"
  },
  "Updateable": false,
  "Version": "ibm-v2.0-0-r46-0-gbed584c"
}
```
There is no indication if this is Host or BMC firmware.

On Supermicro they implemented it as `/redfish/v1/UpdateService/FirmwareInventory/BMC` and `/redfish/v1/UpdateService/FirmwareInventory/PNOR` 

Currently being looked at by openbmc team: https://ibm-systems-power.slack.com/archives/CBTMJ2Q8Z/p1547580065013400

```

**Comment by jjohnson42** [comment]
Note, in redfish it is a very bad idea to presume URLs.  URLs have to be discovered.  This is one criticism I have had from the beginning that makes it very aggravating to automate.

In fact, /redfish/v1/Systems/1/ may be valid on one platform, but another platform might call that invalid and instead require /redfish/v1/Systems/1.

Though it's nowhere near complete, see how https://github.com/openstack/pyghmi/blob/master/pyghmi/redfish/command.py scans the hypermedia topology to find things that it supports.  Unfortunately this is required.  pyghmi's approach is to cache the map so that repeated queries are quicker, but it means a stateless management approach is doomed to be slow or incorrect.   confluent keeps command objects persistent to allow these hits to only be taken occasionally rather than every time.
