### ISSUE TITLE
[xcat-ansible]customize and use patch/postinst for mlnx/cuda9.2 support with Ansible

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#56]
As a user, how to customize and use patch/postinst for mlnx/cuda9.2 support ==> 3 points
* reference https://github.ibm.com/vhu/c910env/tree/master/ansible/demo

**Comment by whowutwut** [comment]
I’ve already complete this task

**Comment by whowutwut** [comment]
Oh this is for the patch.  Ok this work is not done yet

**Comment by zet809** [comment]
Our plan is changed, the priority is very low, let's close it and open when plan to do.
