### ISSUE TITLE
Investigate redfish libs and tools whether could support xcat commands

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#563]
Investigate existed redfish python libs and tools to check whether could call them directly to get info xcat needed.

**Comment by xuweibj** [comment]
**Libs**
* DMTF/python-redfish-library
https://github.com/DMTF/python-redfish-library

Could do **login**, **post**, **patch**, **put**, **get**.
Could replace ``request``.

* openstack/python-redfish  -- 38%
https://github.com/openstack/python-redfish/tree/master/redfish

login

rsetboot (set)

rpower
bmcreboot/stat/reset/boot

rspconfig
ipv4/hostname (get) 

rinv
firmware version/model/serial
cpu count/model
memory total

rvitals
temperatures/fans/leds

* openstack/sushy    -- 34%
https://github.com/openstack/sushy

login
rsetboot 

rpower
bmcreboot/reset/stat/on/off/boot

rspconfig
hostname (get)

rvitals
leds

rinv
model/serial/uuid

**Tool**
* DMTF/Redfishtool -- 58%
https://github.com/DMTF/Redfishtool

login
rpower
rsetboot
rbeacon

rinv
model/serial/firmware/uuid

rspconfig
ip/netmask/gateway/vlan/hostname/ntpservers (get)

reventlog
list

rvitals
temperatures/fans/leds/power

**Comment by zet809** [comment]
Based on the investigation, it shows:
1. all of public libraries can not fulfill our requirement, more than 60% functions are not include, and it maybe very slow if we want to commit code for them(especially for openstack/python-redfish and openstack/sushy, if Jarrod maintain pyghmi, this repo will be easier, but same problem if not owned by Jarrod)
2. for redfish interface, it is a very simple request/response mode, the common logic such as logon, send request and get response only takes less than 10% of our effort, no much value to leverage new library.
3. we can modify our code structure, and provide libraries like: 
    1. general Redfish interface with more action based functions.
    2. a redfish tool can do hardware management for groups of nodes.
