### ISSUE TITLE
restore x86, p8, p9 physical machine test environment

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#589]
what to do:

Due to the x86, p8 physical machine test environment have been broken for long time. Restore them.

* [x] find new suitable x86, p8 physical machine, one for each type, update [document](https://github.ibm.com/xcat2/team_process/blob/master/FVT/docs/Automation_Development_Environment_Hardware_List.md)

* [x] using the result of https://github.com/xcat2/xcat2-task-management/issues/588 to test 

* [x] add or update project configuration

**Comment by tingtli** [comment]
x86_64 physical machines are installed with rhels7.6
```
c910f04x37
c910f04x38
c910f04x42
```
