### ISSUE TITLE
Support nodeset <cumulus_switch> osimage command for cumulus switches 

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat2-task-management#60]
Epic #59 
nodeset performs the following operations:
(1) find the "*.bin" file under the first entry in osimage.pkgdir, then copy the "*.bin" to /install/osimages/cumulus3.5.2-armel
(2)assign the node.provmethod to the osimage name
(3)run "makedhcp -a ", generate the dhcp lease with full path to the bin file in default-url option
```
nodeset mid05tor12 osimage=cumulus3.5.2-armel
[root@briggs01 ~]# lsdef mid05tor12
Object name: mid05tor12
    groups=switch,edge_switch
    ip=172.11.205.12
    mac=xx:xx:xx:xx:xx:xx
    mgt=switch
    netboot=onie
```

**Comment by cxhong** [comment]
opened in the wrong place.

**Comment by zet809** [comment]
Hi, @cxhong , what is the purpose of this isuse? A task? The xcat2-task-management repo is used to trace tasks from 2.14, I don't think it is wrong to trace tasks here.
