### ISSUE TITLE
investigate mapping xcat node to node object in confluent

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#601]
* [x] investigate node object model in confluent
* [x] investigate how to add/remove node attribute in confluent
* [x] mapping xcat node with confluent node object
* [x] have nodes/<xcatnode>/power/state work for xcatnode ==> https://github.com/xcat2/confluent/pull/103/commits/5702f7372b1e921cdf566d0ea883ead79847a121

**Comment by jjohnson42** [comment]
FYI:
https://github.com/xcat2/confluent/blob/master/confluent_server/confluent/config/attributes.py

**Comment by zet809** [comment]
Thank you very much, @jjohnson42
