### ISSUE TITLE
[rhels8 test] Set test projects in automation development env to do regression for no-rhel8.0 OSs

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#631]
what to do:

* Set test projects in automation development env to do regression for no-rhel8.0 OSs

* [x] rhels6.10 + lpar
* [x] rhels 7.6 + lpar
* [x] rhels 7.6 + x86 vm
* [x] rhels 7.6 + p8  vm
* [x] pegas 1.2 + p9 vm
* [x] ubuntu 16.4.5  + p8 vm
* [x] ubuntu 16.4.5  + x86 vm
* [x] ubuntu 18.4.1 + x86 vm
* [x] ubuntu 18.4.1 + p8 vm
* [x] ubuntu 18.4.1 + p9 vm
* [x] sles 12.3 + p8 vm
* [x] sles 12.3 + x86 vm
* [x] sles 11.4 + lpar

Test packages:
```
    xcat-core:  the result of #630 
    xcat-dep linux:  http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201811190436.tar.bz2
    xcat-dep debain: http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/xcat-dep-ubuntu-201811200025.tar.bz2
```

**Comment by tingtli** [comment]
The automation projects are setup in http://10.3.17.9:8080/view/Specific%20Build%20Test/
