### ISSUE TITLE
[RH8] Revise the default disk partition layout for xCAT compute node running RHEL 8

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#643]
Currently, default `/dev/mapper/xcatvg-root` is 8G in RH8 compute node. 
In the past, xCAT generate a very large size of ``/``, now ``/`` is only 8G. I think 8G is not proper as a default ``/`` partition size.
For example, if the compute node is used as xCAT service node, customer may like to save some diskful or diskless OS under local ``/install`` directory, 8G is too mall.

So I file this issue here to trace this RH8 partition strategy.

**Comment by neo954** [comment]
See https://github.com/xcat2/xcat-core/issues/842

**Comment by robin2008** [comment]
We may need a better partition schema suitable for xCAT stateful node:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/installing_and_deploying_rhel/partitioning-reference_graphical-installation#recommended-partitioning-scheme_partitioning-reference

**Comment by neo954** [comment]
## Scenario ##

The default partition policy of osimage, `rhels8.0.0-ppc64le-install-compute` should allow the operating system to be deployed on a system with such a small size hard disk drive. Say, 10GB or 8GB.

**Comment by immarvin** [comment]
I suggest set the maxsize of partitions to be a percentage instead of absolute value.  the root partition can be 30%

**Comment by neo954** [comment]
Will close this one.
