### ISSUE TITLE
Verify rhel8 mn can provision legacy OSs

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#646]
what to do:

Verify rhel8 mn can provision legacy OSs

  * [x] rhel8 x86 mn to deploy rhel6.10 x86 diskful cn
  * [x] rhel8 x86 mn to deploy rhel7.6 x86 diskful cn
  * [x] rhel8 x86 mn to deploy sles12.3 x86 diskful cn
  * [x] rhel8 x86 mn to deploy sles11.4 x86 diskful cn
  * [x] rhel8 x86 mn to deploy ubuntu16.04.5 x86 diskful cn
  * [x] rhel8 x86 mn to deploy ubuntu18.04.1 x86 diskful cn

  * [x] rhel8 ppcle mn to deploy pegas1.2 ppcle diskful cn
  * [x] rhel8 ppcle mn to deploy rhel7.6 ppcle diskful cn
  * [x] rhel8 ppcle mn to deploy sles12.3 ppcle diskful cn
  * [x] rhel8 ppcle mn to deploy ubuntu16.04.5 ppcle diskful cn
  * [x] rhel8 ppcle mn to deploy ubuntu18.04.1 ppcle diskful cn

  * [x] rhel8 x86 mn to deploy  rhel7.6 x86 diskless cn (export image from rhel7.6 mn, deploy from rhel8 mn)
  * [x] rhel8 ppcle mn to deploy  rhel7.6 ppcle diskless cn (export image from rhel7.6 mn, deploy from rhel8 mn)
   
using:
```
xcat-core : master daily build
xcat-dep :  download from https://github.com/xcat2/xcat2-task-management/issues/443
```

**Comment by xuweibj** [comment]
rhel8 x86 mn to deploy rhel6.10 x86 diskful cn -- Open issue https://github.com/xcat2/xcat-core/issues/6119
