### ISSUE TITLE
Add test case for issue 2659:/etc/fstab does not take effect in diskless compute node 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#69]
Add test case for issue xcat2/xcat-core#2659

**Comment by bybai** [comment]
There is no any code changes for issue xcat2/xcat-core#2659 now, so we do not need test case enhancements for this issue. Thanks.

**Comment by hu-weihua** [comment]
It seems the requirement of this task was outdated. Cancel this task.
