### ISSUE TITLE
Test rspconfig python version 

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#9]
what to do:

* [ ] offer test plan: [Test Design of rspconfig python version](https://github.com/xcat2/xcat-core/wiki/Test-Design-of-rspconfig-python-version)
* [ ] finish test depending on above test plan

**Comment by jjohnson42** [comment]
So... confluent is already a python implementation of many things, including rspconfig.... just fyi....

**Comment by daniceexi** [comment]
@jjohnson42 currently the Python is mostly used for openbmc support. For general BMC we might leverage the code in the Confluent. Thanks.

**Comment by tingtli** [comment]
Finished the test, see bugs
https://github.com/xcat2/xcat-core/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+author%3Atingtli+rspconfig
