### ISSUE TITLE
Add test case for issue 3497 : reventlog does not make too much sense

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#90]
Add test case for issue xcat2/xcat-core#3497

**Comment by tingtli** [comment]
I think our current reventlog bucket could cover the test for issue #3497. The cases list is.
reventlog_null
reventlog_all
reventlog_clear
reventlog_numofentries
reventlog_s_openbmc

The cases covers reventlog's all  options . So we don't need to add cases for that issue.
